
project_id = "ngpenivrpznqycgkibrs"

# The port to use for the API URL.
api_port = 54321

# The port to use for the Auth URL.
auth_port = 54321

# The port to use for the Storage URL.
storage_port = 54321

# The port to use for the Realtime URL.
realtime_port = 54321

# The port to use for the Studio URL.
studio_port = 54321

# Email testing
[email_testing]
enable_email_testing = true

[functions.send-assessment-email]
verify_jwt = true

[functions.send-supabase-email]
verify_jwt = true

[functions.send-email-resend]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false
