
// Database schema types - auto-generated from Supabase
export interface Database {
  public: {
    Tables: {
      // Tables will be auto-generated by Supabase CLI
      [key: string]: {
        Row: Record<string, any>
        Insert: Record<string, any>
        Update: Record<string, any>
        Relationships: any[]
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, any>
        Relationships: any[]
      }
    }
    Functions: {
      [key: string]: {
        Args: Record<string, any>
        Returns: any
      }
    }
    Enums: {
      [key: string]: string
    }
    CompositeTypes: {
      [key: string]: Record<string, any>
    }
  }
}

// Export the Database type for use in other files
export type { Database }
