// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngpenivrpznqycgkibrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncGVuaXZycHpucXljZ2tpYnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzc3MzAsImV4cCI6MjA1OTY1MzczMH0.JKYV2dCMsszTqThVW1Vd9mQX8OlJV-dAgQfuxSD5HxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);